name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

  publish:
    name: Publish plugin to Microsoft marketplace
    needs: release-please
    if: ${{ needs.release-please.outputs.tag-name }}
    runs-on: ubuntu-latest
    environment: marketplace
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          check-latest: true

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Publish it
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
